rinkesh:main.o read.o add.o print.o save.o count.o rev.o del.o
	cc main.o add.o print.o count.o -o rinkesh
main.o:main.c
	cc -c main.c
add.o:add.c
	cc -c add.c
print.o:print.c
	cc -c print.c
count.o:count.c
	cc -c count.c
